// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGKE7HsnWYeuDjEfZaDi75h1s1csk28Uo',
    appId: '1:284917510863:web:672277cfd9ee26e129bdba',
    messagingSenderId: '284917510863',
    projectId: 'mobile-application-d13e0',
    authDomain: 'mobile-application-d13e0.firebaseapp.com',
    storageBucket: 'mobile-application-d13e0.firebasestorage.app',
    measurementId: 'G-27CRSRGBE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDMq-I7QsWB8b-UQFQhrkhCUZAb-j9zUg',
    appId: '1:284917510863:android:b53188bb03bd547b29bdba',
    messagingSenderId: '284917510863',
    projectId: 'mobile-application-d13e0',
    storageBucket: 'mobile-application-d13e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJxJ4rIth-n8N65zFnqWVqRtlaerTipyg',
    appId: '1:284917510863:ios:7c8cd4ab280ec92f29bdba',
    messagingSenderId: '284917510863',
    projectId: 'mobile-application-d13e0',
    storageBucket: 'mobile-application-d13e0.firebasestorage.app',
    iosBundleId: 'com.example.mobilePhoneSalesManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJxJ4rIth-n8N65zFnqWVqRtlaerTipyg',
    appId: '1:284917510863:ios:7c8cd4ab280ec92f29bdba',
    messagingSenderId: '284917510863',
    projectId: 'mobile-application-d13e0',
    storageBucket: 'mobile-application-d13e0.firebasestorage.app',
    iosBundleId: 'com.example.mobilePhoneSalesManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGKE7HsnWYeuDjEfZaDi75h1s1csk28Uo',
    appId: '1:284917510863:web:a1d8d62a4ed609ba29bdba',
    messagingSenderId: '284917510863',
    projectId: 'mobile-application-d13e0',
    authDomain: 'mobile-application-d13e0.firebaseapp.com',
    storageBucket: 'mobile-application-d13e0.firebasestorage.app',
    measurementId: 'G-32CPXWW4QM',
  );
}
